
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Hanz\Development\Python\Exercise\matdas-py-integral\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("443x527")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 527,
    width = 443,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    23.0,
    22.0,
    anchor="nw",
    text="Hello, Integralian!",
    fill="#000000",
    font=("Consolas Bold", 16 * -1)
)

canvas.create_text(
    23.0,
    48.0,
    anchor="nw",
    text="Integral Calculator",
    fill="#000000",
    font=("Consolas Bold", 24 * -1)
)

canvas.create_text(
    23.0,
    104.0,
    anchor="nw",
    text="Choose one:",
    fill="#000000",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    23.0,
    388.0,
    anchor="nw",
    text="Result: ",
    fill="#000000",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    206.0,
    450.0,
    anchor="nw",
    text=". . .",
    fill="#000000",
    font=("Inter Bold", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=227.0,
    y=131.0,
    width=193.0,
    height=45.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=23.0,
    y=131.0,
    width=193.0,
    height=45.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=23.0,
    y=322.0,
    width=397.0,
    height=45.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    49.0,
    248.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    252.5,
    251.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=89.0,
    y=229.0,
    width=327.0,
    height=42.0
)
window.resizable(False, False)
window.mainloop()
